# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np
arr1 = np.random.random((3,3,3))
print(arr1)

[[[0.09018494 0.53792896 0.83630395]
  [0.04989557 0.21253981 0.57820663]
  [0.18847172 0.83450024 0.357618  ]]

 [[0.72058882 0.29321621 0.43966124]
  [0.2048661  0.17013501 0.68100436]
  [0.19559966 0.36337011 0.72807262]]

 [[0.01218667 0.50621161 0.85765645]
  [0.95112289 0.29815803 0.47997565]
  [0.81258399 0.43860927 0.65337197]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
arr2 =np.zeros((5,5))

arr2[1][0]=arr2[2][0]=arr2[3][0]=arr2[4][0]=1
arr2[2][1]=arr2[3][1]=arr2[4][1]=2
arr2[3][2]=arr2[4][2]=3
arr2[4][3]=4

print(arr2)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 2. 0. 0. 0.]
 [1. 2. 3. 0. 0.]
 [1. 2. 3. 4. 0.]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
arr3 = np.zeros((8, 8), dtype=int)
arr3[1::2,::2]=1
arr3[::2,1::2]=1
arr3

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 4. Normalize a 5x5 random matrix

In [4]:
arr4=np.random.random((5,5))
print(arr4)

mx=arr4.max()
mn=arr4.min()

arr4=(arr4-mn)/(mx-mn)
print("\n\nNormalized array is....")
print(arr4)

[[0.91068125 0.5893412  0.57250707 0.87621679 0.82632049]
 [0.25618419 0.89518467 0.60992611 0.30741273 0.95841299]
 [0.99351611 0.71620687 0.12088849 0.3370965  0.21749103]
 [0.69354371 0.75319163 0.70741936 0.21765853 0.3371163 ]
 [0.71888373 0.51753532 0.45919098 0.1744581  0.39617876]]


Normalized array is....
[[0.90507422 0.53683003 0.51753872 0.86557918 0.80839982]
 [0.15504402 0.88731569 0.5604196  0.2137501  0.95977309]
 [1.         0.68221354 0.         0.24776663 0.11070305]
 [0.65624237 0.72459675 0.67214337 0.110895   0.24778932]
 [0.68528113 0.45454306 0.38768253 0.06138886 0.31547279]]


# 5.  How to find common values between two arrays?

In [5]:
arr5=np.array([[10,20,30],[40,50,60]])
arr6=np.array([[10,100,20],[40,400,50]])
print(arr5)
print(arr6)

print("The common values are.....\n",np.intersect1d(arr5,arr6))

[[10 20 30]
 [40 50 60]]
[[ 10 100  20]
 [ 40 400  50]]
The common values are.....
 [10 20 40 50]


# 6.How to get the dates of yesterday, today and tomorrow?

In [6]:
yesterday=np.datetime64('today','D')-np.timedelta64(1, 'D')
print("Yesterday date:",yesterday)

today=np.datetime64('today','D')
print("today's date:",today)

tomorrow=np.datetime64('today','D')+np.timedelta64(1,'D')
print("tommorow's date:",tomorrow)


Yesterday date: 2020-08-04
today's date: 2020-08-05
tommorow's date: 2020-08-06


# 7. Consider two random array A and B, check if they are equal

In [7]:
arr7=np.eye(5,5)
arr8=np.zeros_like(arr7)

print(arr7,"\n\n",arr8)

chck=np.allclose(arr7,arr8)
print(chck)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 

 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [8]:
n=np.random.random(10)
print(n)

n[n.argmax()]=0
print(n)

[0.78489388 0.76491105 0.86609465 0.17661198 0.70895659 0.73288034
 0.90486238 0.01130226 0.94819126 0.49923623]
[0.78489388 0.76491105 0.86609465 0.17661198 0.70895659 0.73288034
 0.90486238 0.01130226 0.         0.49923623]


# 9. How to print all the values of an array?

In [9]:
arr9=np.array([[1,2,3],[4,5,6]])
for i in arr9:
    for k in i:
        print(k)

1
2
3
4
5
6


# 10.Subtract the mean of each row of a matrix

In [10]:
y=np.random.random((4,5))
print(y)

y=y-y.mean(axis=1,keepdims=True)
print("\n\nAfter Subtracting mean...\n\n",y)

[[0.97461573 0.85013344 0.31521133 0.6989825  0.55949179]
 [0.75178944 0.5662134  0.80916185 0.93478125 0.26911728]
 [0.32558325 0.55211309 0.26931607 0.55522352 0.440955  ]
 [0.38150514 0.80514367 0.95862392 0.09497552 0.10758655]]


After Subtracting mean...

 [[ 0.29492877  0.17044648 -0.36447563  0.01929554 -0.12019517]
 [ 0.08557679 -0.09999925  0.14294921  0.26856861 -0.39709536]
 [-0.10305494  0.12347491 -0.15932212  0.12658534  0.01231681]
 [-0.08806182  0.33557671  0.48905696 -0.37459144 -0.36198041]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [11]:
l = np.random.random((2,2))
print(l)
m=np.ones_like(l)
l+=m
print("\n\nUpdated Matrix\n\n",l)

[[0.17436311 0.87410606]
 [0.83314702 0.36168701]]


Updated Matrix

 [[1.17436311 1.87410606]
 [1.83314702 1.36168701]]


# 12.How to get the diagonal of a dot product?

In [12]:
print(arr7)
arr7.dot(np.ones_like(arr7))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# 13.How to find the most frequent value in an array?

In [13]:
ap = np.random.randint(0,10,30)
print(ap)

print(np.bincount(ap).argmax())


[5 7 8 1 7 2 8 7 9 2 7 8 9 9 5 0 2 3 7 4 1 7 5 1 1 0 8 5 9 4]
7


# 14.How to get the n largest values of an array

In [14]:
ap = np.random.randint(0,10,30)
print(ap)

print(ap[np.argsort(ap)[-1:]])

[3 8 6 7 8 6 1 0 9 5 0 0 0 7 3 0 9 2 2 2 4 5 2 2 1 1 1 7 4 8]
[9]


# 15.How to create a record array from a regular array?

In [15]:
a = np.array([('Red',34.9,40),('Yellow',67.3,78)])
a

array([['Red', '34.9', '40'],
       ['Yellow', '67.3', '78']], dtype='<U6')

In [16]:
result=np.core.records.fromarrays(a.T,names='a,b')
result

rec.array([('Red', '34.9', '40'), ('Yellow', '67.3', '78')],
          dtype=[('a', '<U6'), ('b', '<U6'), ('f2', '<U6')])